### ISSUE TITLE
Loader/Poke

### ISSUE THREAD

**Issue by Cyb3rn0id** [teiram/dandanator-mini#1]
If I insert Pokes, the "L - Loader" menù does not appear. It's a wanted behaviour or a bug?

**Comment by teiram** [comment]
This is the expected behaviour. The loader is only added to the romset in case there is enough space for it. There is a zone on the romset structure of compressed data shared by pokes, the firmware loader code and some other stuff .

**Comment by Cyb3rn0id** [comment]
It would be better put an advice when there is no more space for the loader: in this case one can think to remove some pokes or a games for making space to loader. Now there is no method to understand if loader will be present or not.
I've tried to use dandanator without loader, using only audio upload: there is no way to make audio upload work on all my pcs: i've tried a lot of cables, settings...nada: I must reprogram the flash using a programmer and remove a game to make loader available. 
If you can make this mod it will be great: a simple label that says "LOADER available" or "loader not available" when one insert/remove games or pokes.

**Comment by teiram** [comment]
You are right, the problem is that we only know if enough room is available at romset generation time, because some of the items are only compressed at that moment. So we would need to recompress things like pokes, background screen,... on any change to put an advice before trying to generate the romset. I will try to think about it and find a suitable solution though.

Regarding your audio problems, you are not alone. Modern PCs don't normally provide a sufficient output for the mostly deaf Spectrum ULA. I got decent results with an Stereo cable and the STEREOINV setting in the generator, but it depends a lot on the source PC and on the target Spectrum.

**Comment by Cyb3rn0id** [comment]
Now I've understood. Thank you. Maybe a simple window at the end of rom generation with the message "loader was included" will be very helpful
