### ISSUE TITLE
ROM layout / format description

### ISSUE THREAD

**Issue by gazsp** [teiram/dandanator-mini#3]
Hi there,

I'd like to write an alternative ROM builder command line tool using C.

Is there any documentation anywhere about what the ROM layout should look like (looking at the Java / slot 1 code the ROM obviously follows some custom slot / chunk format with blocks optionally be compressed)?

I guess I could get all this from reading the code, but I'd imagine you had to document it somewhere to write the code in the first place? :-) 

Regards,
Gaz.

**Comment by Silveriomrs** [comment]
Hi, 
If I am not wrong, there is not any documentation.
I was requesting it to develop a new Java LTS version, only source code is aviable but it is not documented as you can see.

Maybe we could study the code together to develop both ideas, your command line tool and my GUI based in a LTS and fresh Java version.

**Comment by teiram** [comment]
Hi,
there is some internal documentation we will try to clean up a bit and make it available in the next days.

The format has been evolving as the device added support for more features. Each major version of the generator had normally included changes in the rom layout, but the generator includes importing features for older versions (see the different DandanatorMiniImporter implementations in packages com.grelobites.romgenerator.handlers.dandanatormini.v*). Roms generated with an older version are automatically detected upon an import attempt and handled with a suitable importer.
The main code to assemble a current rom is in DandanatorMiniV9RomSetHandler.exportRomSet and studying that code you should be able to understand the format. Take into account that it uses compression intensively for different parts of the first slot (the so called Slot Zero in the code) and tries to get the best organization possible for the game slots (compressed or not) to avoid lost space due to fragmentation.
Regarding @Silveriomrs comment about porting it to a new Java LTS version, the current version (in master branch) can be run on Java 17 (and any version >= java8) with or without the javafx extensions, that are bundled into the assembled artifact. There is an automatically build binary that can be found in the packages section of the project (normally showing below the Releases section, on the right side)

**Comment by Silveriomrs** [comment]
> Regarding @Silveriomrs comment about porting it to a new Java LTS version, the current version (in master branch) can be run on Java 17 (and any version >= java8) with or without the javafx extensions, that are bundled into the assembled artifact. There is an automatically build binary that can be found in the packages section of the project (normally showing below the Releases section, on the right side)

Hi, 
I'm sorry, but I don't understand it. Looking for the main branch it shows a warning that requires Java8 + other things...

and just running the jar on my system that get out:

![imagen](https://user-images.githubusercontent.com/33696002/209441711-771bb289-829d-43ff-814f-e84af30f1b4f.png)

But also from Eclipse:
![imagen](https://user-images.githubusercontent.com/33696002/209441778-f3703226-464e-4851-82a1-aafd24975e86.png)


Pretty sure it is my mistake and misunderstanding, but ... it doesn't work for me.
Must add, I am not very Maven friendly, so perhaphs something is wrong by that point.

Whatever, the jar doesn't work on my system as you described should do. (if I didn't misunderstood you). That is why I want to port it for any user without care about JavaFX installed or not, or be forced to use Java8

**Comment by teiram** [comment]
Hi @Silveriomrs,
I think your branch is not in sync with master. I just tried from scratch:
```
mkdir test && cd test
git clone https://github.com/teiram/dandanator-mini.git
cd dandanator-mini
mvn install
java -jar target/dandanator-mini-10.4.1.jar
```

And I'm on:
```
C:\Users\mteira\Desktop\test\dandanator-mini\target>java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
```

But should work also with any jdk from 8 onwards

Also, when you say that the jar doesn't work in your system, have you tried with the one available here under the section Packages?

**Comment by Silveriomrs** [comment]
> Also, when you say that the jar doesn't work in your system, have you tried with the one available here under the section Packages?

Hi :) Following your instructions it worked fine on my system (Computer+OS+jvm).

And now I understand the point was that I have used the version on: http://www.dandare.es/Descargas/dandanator-mini-10.3.jar , what is not the same version, and doesn't work on my System (OS+Java version).

No, I didn't try last version here, but what I replied on my Eclipse some months ago.

Well... my main reason is not needed any more. But at any case... How could I help?

**Comment by teiram** [comment]
Hello @Silveriomrs,
glad to know it worked.  :)
I think the next steps related to this topic would be for us to make available the ROM format documentation. With that and the sources here it should be possible for @gazsp to check and see how feasible it would be to write the C CLI. 
Just take into account that to mimic some features existing in the current generator, an embedded emulator would be needed (in case you want to be able to convert TAP files into snapshots on the fly , what this generator is able to provide too.

**Comment by teiram** [comment]
Hello again,
I've just pushed a change including the [ROM layout specification](https://github.com/teiram/dandanator-mini/blob/master/doc/ZXDan%20-%20Slot%200%20-%20Release.pdf) for the current version.
Hope it is helpful for your project

**Comment by gazsp** [comment]
Awesome, thanks!
